import type { Metadata } from "next";
import { Rubik, Montserrat } from "next/font/google";
import "./globals.scss";
import ReduxProvider from "@/src/providers/ReduxProvider";

const rubikSans = Rubik({
  variable: "--font-rubik-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const montserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubikSans.variable} ${montserratSans.variable}`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
